# Profile-specific schemas

Profile:
  type: object
  properties:
    id:
      type: integer
      description: Profile ID
    address:
      type: string
      description: Ethereum address
    nickname:
      type: string
      description: Profile nickname
    ensName:
      type: string
      description: ENS name (if registered)
    avatarUrl:
      type: string
      description: URL to avatar image
    bio:
      type: string
      description: User biography
    createdAt:
      type: string
      format: date-time
      description: Creation timestamp
    updatedAt:
      type: string
      format: date-time
      description: Last update timestamp
    score:
      type: number
      description: Profile reputation score
    xp:
      type: integer
      description: Profile experience points
    isShadowProfile:
      type: boolean
      description: Whether this is a shadow profile

ActivityActor:
  type: object
  properties:
    profileId:
      type: integer
      description: Profile ID
    name:
      type: string
      description: Actor name
    avatarUrl:
      type: string
      description: URL to avatar image

ProfileWithActor:
  allOf:
    - $ref: '#/Profile'
    - type: object
      properties:
        invitedBy:
          type: integer
          description: Profile ID of the user who invited this profile
        actor:
          $ref: '#/ActivityActor'
        inviterActor:
          $ref: '#/ActivityActor'

CredibilityProfile:
  type: object
  properties:
    id:
      type: integer
    address:
      type: string
    nickname:
      type: string
    ensName:
      type: string
    avatarUrl:
      type: string
    score:
      type: number

XpProfile:
  type: object
  properties:
    id:
      type: integer
    address:
      type: string
    nickname:
      type: string
    ensName:
      type: string
    avatarUrl:
      type: string
    totalXp:
      type: integer

ProfileWithXAttestation:
  type: object
  properties:
    profileId:
      type: integer
    twitterUserId:
      type: string
    twitterUsername:
      type: string
    address:
      type: string

ProfileStats:
  type: object
  properties:
    activeProfiles:
      type: integer
      description: Total number of active (non-archived) profiles
    invitesAvailable:
      type: integer
      description: Total number of available invites across all profiles
